"""VOLT OS — Backend Dev Agent."""
from src.agents.interface import AgentInterface, AgentContext, AgentResult, AgentStatus
from src.model_router.router import ModelRouter
import time


class BackendDevAgent(AgentInterface):
    """Generates backend code (APIs, databases, services)."""

    def __init__(self, model_router: ModelRouter):
        self.model_router = model_router
        self.context: AgentContext | None = None

    def initialize(self, context: AgentContext) -> None:
        self.context = context

    def execute(self, task: dict) -> AgentResult:
        start = time.time()
        try:
            selection = self.model_router.select(task_type="code_generation", complexity="high", agent_preferences=[{"model": "claude-sonnet-4", "reason": "complex reasoning, API design"}])
            code = {"files": [{"path": "src/api/routes.py", "content": "# Generated by VOLT OS Backend Dev Agent", "language": "python"}], "manifest": {"dependencies": {"fastapi": "^0.115.0", "sqlalchemy": "^2.0.0"}}, "build_status": "success"}
            api_spec = {"openapi": "3.1.0", "paths": {}}
            duration_ms = int((time.time() - start) * 1000)
            return AgentResult(status=AgentStatus.COMPLETED, output_artifacts={"code": code, "build_report": {"build_status": "success"}, "api_spec": api_spec}, cost_usd=selection.estimated_cost_usd, duration_ms=duration_ms)
        except Exception as e:
            return AgentResult(status=AgentStatus.FAILED, error=str(e), duration_ms=int((time.time() - start) * 1000))

    def health_check(self) -> dict:
        return {"status": "healthy", "agent": "backend_dev"}

    def cleanup(self) -> None:
        self.context = None

    def output_types(self) -> list[str]:
        return ["code", "api_spec"]

    def input_types(self) -> list[str]:
        return ["architecture_spec", "task_breakdown"]
