"""VOLT OS — Frontend Dev Agent."""
from src.agents.interface import AgentInterface, AgentContext, AgentResult, AgentStatus
from src.model_router.router import ModelRouter
import time


class FrontendDevAgent(AgentInterface):
    """Generates frontend code (React/Next.js/Flutter/etc)."""

    def __init__(self, model_router: ModelRouter):
        self.model_router = model_router
        self.context: AgentContext | None = None

    def initialize(self, context: AgentContext) -> None:
        self.context = context

    def execute(self, task: dict) -> AgentResult:
        start = time.time()
        try:
            arch = self.context.input_artifacts.get("architecture_spec", {})
            selection = self.model_router.select(task_type="code_generation", complexity="medium", agent_preferences=[{"model": "claude-sonnet-4", "reason": "code generation"}])
            code = self._generate_code(arch)
            duration_ms = int((time.time() - start) * 1000)
            return AgentResult(status=AgentStatus.COMPLETED, output_artifacts={"code": code, "build_report": {"build_status": "success", "total_files": len(code.get("files", [])), "total_lines": 0}}, cost_usd=selection.estimated_cost_usd, duration_ms=duration_ms)
        except Exception as e:
            return AgentResult(status=AgentStatus.FAILED, error=str(e), duration_ms=int((time.time() - start) * 1000))

    def health_check(self) -> dict:
        return {"status": "healthy", "agent": "frontend_dev"}

    def cleanup(self) -> None:
        self.context = None

    def output_types(self) -> list[str]:
        return ["code"]

    def input_types(self) -> list[str]:
        return ["architecture_spec", "task_breakdown"]

    def _generate_code(self, arch: dict) -> dict:
        components = arch.get("components", [])
        frontend = next((c for c in components if c.get("type") == "frontend"), None)
        return {"files": [{"path": "src/app/page.tsx", "content": "// Generated by VOLT OS Frontend Dev Agent", "language": "typescript"}], "manifest": {"dependencies": {"next": "^15.0.0", "react": "^19.0.0"}, "scripts": {"dev": "next dev", "build": "next build"}}, "build_status": "success"}
